/**
 * Assessment: TOPS Technologies - Software Engineering M3-A1
 * Section D - Step 1: AI's Original Code
 * 
 * Generated by AI Assistant based on prompt in prompt.txt
 */

#include <stdio.h>

int main() {
    int arr[10];
    int sum = 0;
    int min = 0;   /* AI Bug: Initialized to 0 instead of arr[0]; fails for negative sets */
    int max = 0;   /* AI Bug: Initialized to 0 instead of arr[0]; fails for negative sets */
    float mean;
    int i, j, temp;

    printf("Enter 10 integers:\n");
    for (i = 0; i < 10; i++) {
        scanf("%d", &arr[i]);
        sum += arr[i];
    }

    /* Find min and max */
    for (i = 0; i < 10; i++) {
        if (arr[i] < min) {
            min = arr[i];
        }
        if (arr[i] > max) {
            max = arr[i];
        }
    }

    mean = (float)sum / 10.0;

    /* Bubble sort */
    for (i = 0; i < 9; i++) {
        for (j = 0; j < 9 - i; j++) {
            if (arr[j] > arr[j + 1]) {
                temp = arr[j];
                arr[j] = arr[j + 1];
                arr[j + 1] = temp;
            }
        }
    }

    printf("\nSorted Array: ");
    for (i = 0; i < 10; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");

    printf("Minimum: %d\n", min);
    printf("Maximum: %d\n", max);
    printf("Mean: %.2f\n", mean);

    /* Closeness comparison */
    float dist_min = mean - min;
    float dist_max = max - mean;

    /* AI Bug: Direct float equality comparison without epsilon tolerance; */
    /* also misclassifies all identical values as "midway" */
    if (dist_min < dist_max) {
        printf("The mean is closer to the minimum.\n");
    } else if (dist_max < dist_min) {
        printf("The mean is closer to the maximum.\n");
    } else {
        printf("The mean is exactly midway between them.\n");
    }

    return 0;
}
